window.FLEGMA_SLOVAK_FOODS = [
  { id: 'seed-mlieko-polotucne', name: 'Mlieko polotucne 1.5%', kcal: 47, protein: 3.4, carbs: 4.8, fat: 1.5, sugar: 4.8, fiber: 0 },
  { id: 'seed-mlieko-plnotucne', name: 'Mlieko plnotucne 3.5%', kcal: 64, protein: 3.3, carbs: 4.8, fat: 3.5, sugar: 4.8, fiber: 0 },
  { id: 'seed-maslo', name: 'Maslo', kcal: 744, protein: 0.7, carbs: 0.6, fat: 82, sugar: 0.6, fiber: 0 },
  { id: 'seed-smotana-12', name: 'Smotana na varenie 12%', kcal: 136, protein: 3, carbs: 4, fat: 12, sugar: 4, fiber: 0 },
  { id: 'seed-smotana-kysla', name: 'Kysla smotana 16%', kcal: 166, protein: 2.8, carbs: 3.6, fat: 16, sugar: 3.6, fiber: 0 },
  { id: 'seed-jogurt-biely', name: 'Jogurt biely', kcal: 63, protein: 3.7, carbs: 5, fat: 3, sugar: 5, fiber: 0 },
  { id: 'seed-jogurt-nizkotucny', name: 'Jogurt biely nizkotucny', kcal: 45, protein: 4.2, carbs: 5.2, fat: 0.5, sugar: 5.2, fiber: 0 },
  { id: 'seed-kefir', name: 'Kefir', kcal: 52, protein: 3.4, carbs: 4.7, fat: 2, sugar: 4.7, fiber: 0 },
  { id: 'seed-bryndza', name: 'Bryndza', kcal: 262, protein: 16, carbs: 1.8, fat: 21, sugar: 1.8, fiber: 0 },
  { id: 'seed-syr-taveny', name: 'Syr taveny', kcal: 260, protein: 13, carbs: 5, fat: 21, sugar: 5, fiber: 0 },
  { id: 'seed-mozzarella', name: 'Mozzarella', kcal: 250, protein: 18, carbs: 2, fat: 19, sugar: 1, fiber: 0 },
  { id: 'seed-syr-gouda', name: 'Syr Gouda', kcal: 356, protein: 25, carbs: 2.2, fat: 27, sugar: 2.2, fiber: 0 },
  { id: 'seed-cottage', name: 'Cottage cheese', kcal: 98, protein: 11, carbs: 3.4, fat: 4.3, sugar: 3.4, fiber: 0 },
  { id: 'seed-lucina', name: 'Lucina', kcal: 260, protein: 8, carbs: 4, fat: 24, sugar: 4, fiber: 0 },
  { id: 'seed-tvaroh-hrudkovity', name: 'Tvaroh hrudkovity', kcal: 118, protein: 16, carbs: 3.5, fat: 4, sugar: 3.5, fiber: 0 },
  { id: 'seed-bravcove-plece', name: 'Bravcove plece', kcal: 220, protein: 18, carbs: 0, fat: 16, sugar: 0, fiber: 0 },
  { id: 'seed-bravcove-kare', name: 'Bravcove kare', kcal: 165, protein: 21, carbs: 0, fat: 9, sugar: 0, fiber: 0 },
  { id: 'seed-bravcova-krkovicka', name: 'Bravcova krkovicka', kcal: 260, protein: 17, carbs: 0, fat: 21, sugar: 0, fiber: 0 },
  { id: 'seed-hovadzie-zadne', name: 'Hovadzie zadne', kcal: 160, protein: 21, carbs: 0, fat: 8, sugar: 0, fiber: 0 },
  { id: 'seed-mlete-maso-mix', name: 'Mlete maso mix', kcal: 250, protein: 17, carbs: 0, fat: 20, sugar: 0, fiber: 0 },
  { id: 'seed-kuracie-stehno', name: 'Kuracie stehno bez koze', kcal: 140, protein: 19, carbs: 0, fat: 7, sugar: 0, fiber: 0 },
  { id: 'seed-kuracie-stehno-koza', name: 'Kuracie stehno s kozou', kcal: 215, protein: 18, carbs: 0, fat: 16, sugar: 0, fiber: 0 },
  { id: 'seed-morcacie-prsia', name: 'Morcacie prsia', kcal: 105, protein: 24, carbs: 0, fat: 1.5, sugar: 0, fiber: 0 },
  { id: 'seed-kuracia-sunka', name: 'Kuracia sunka', kcal: 105, protein: 19, carbs: 1.5, fat: 2.5, sugar: 1, fiber: 0 },
  { id: 'seed-slanina', name: 'Slanina', kcal: 540, protein: 14, carbs: 1, fat: 53, sugar: 0.5, fiber: 0 },
  { id: 'seed-parky', name: 'Parky', kcal: 290, protein: 12, carbs: 3, fat: 25, sugar: 1, fiber: 0 },
  { id: 'seed-klobasa', name: 'Klobasa', kcal: 390, protein: 18, carbs: 2, fat: 34, sugar: 1, fiber: 0 },
  { id: 'seed-salama', name: 'Salama sucha', kcal: 420, protein: 22, carbs: 1, fat: 36, sugar: 0.5, fiber: 0 },
  { id: 'seed-tuniak-vo-vlastnej-stave', name: 'Tuniak vo vlastnej stave', kcal: 116, protein: 26, carbs: 0, fat: 1, sugar: 0, fiber: 0 },
  { id: 'seed-sardinky-olej', name: 'Sardinky v oleji', kcal: 208, protein: 24, carbs: 0, fat: 12, sugar: 0, fiber: 0 },
  { id: 'seed-treska-file', name: 'Treska file', kcal: 82, protein: 18, carbs: 0, fat: 0.7, sugar: 0, fiber: 0 },
  { id: 'seed-muka-hladka', name: 'Muka hladka', kcal: 364, protein: 10, carbs: 76, fat: 1, sugar: 1, fiber: 3 },
  { id: 'seed-muka-polohruba', name: 'Muka polohruba', kcal: 364, protein: 10, carbs: 76, fat: 1, sugar: 1, fiber: 3 },
  { id: 'seed-muka-hruba', name: 'Muka hruba', kcal: 363, protein: 10, carbs: 75, fat: 1.2, sugar: 1, fiber: 3 },
  { id: 'seed-muka-celozrnna', name: 'Muka celozrnna', kcal: 340, protein: 12, carbs: 62, fat: 2.5, sugar: 1.5, fiber: 11 },
  { id: 'seed-krupica', name: 'Krupica', kcal: 360, protein: 11, carbs: 73, fat: 1.2, sugar: 1, fiber: 3 },
  { id: 'seed-struhanka', name: 'Struhanka', kcal: 380, protein: 12, carbs: 72, fat: 5, sugar: 5, fiber: 4 },
  { id: 'seed-rohlik', name: 'Rohlik biely', kcal: 286, protein: 8.5, carbs: 57, fat: 2.5, sugar: 4, fiber: 3 },
  { id: 'seed-zemla', name: 'Zemla', kcal: 275, protein: 8, carbs: 54, fat: 3, sugar: 4, fiber: 3 },
  { id: 'seed-chlieb-konzumny', name: 'Chlieb konzumny', kcal: 250, protein: 8, carbs: 49, fat: 2, sugar: 3, fiber: 5 },
  { id: 'seed-toastovy-chlieb', name: 'Toastovy chlieb', kcal: 265, protein: 8.5, carbs: 49, fat: 4, sugar: 5, fiber: 3.5 },
  { id: 'seed-knedla', name: 'Knedla parena', kcal: 235, protein: 7, carbs: 48, fat: 1.5, sugar: 2, fiber: 2 },
  { id: 'seed-tortilla-psenicna', name: 'Tortilla psenicna', kcal: 310, protein: 8, carbs: 52, fat: 8, sugar: 2, fiber: 3 },
  { id: 'seed-ryza-natural', name: 'Ryza natural varena', kcal: 112, protein: 2.6, carbs: 23, fat: 0.9, sugar: 0.4, fiber: 1.8 },
  { id: 'seed-bulgur-vareny', name: 'Bulgur vareny', kcal: 83, protein: 3.1, carbs: 18.6, fat: 0.2, sugar: 0.1, fiber: 4.5 },
  { id: 'seed-kuskus-vareny', name: 'Kuskus vareny', kcal: 112, protein: 3.8, carbs: 23, fat: 0.2, sugar: 0.1, fiber: 1.4 },
  { id: 'seed-pohanka-varena', name: 'Pohanka varena', kcal: 92, protein: 3.4, carbs: 20, fat: 0.6, sugar: 0.9, fiber: 2.7 },
  { id: 'seed-pecene-zemiaky', name: 'Zemiaky pecene', kcal: 120, protein: 2.5, carbs: 24, fat: 2.5, sugar: 1, fiber: 2.2 },
  { id: 'seed-hranolky-pecene', name: 'Hranolky pecene', kcal: 190, protein: 3, carbs: 30, fat: 7, sugar: 0.5, fiber: 3 },
  { id: 'seed-zemiakova-kasa', name: 'Zemiakova kasa', kcal: 105, protein: 2.2, carbs: 16, fat: 3.5, sugar: 1.5, fiber: 1.5 },
  { id: 'seed-fazula-varena', name: 'Fazula varena', kcal: 127, protein: 8.7, carbs: 22.8, fat: 0.5, sugar: 0.3, fiber: 6.4 },
  { id: 'seed-sosovica-varena', name: 'Sosovica varena', kcal: 116, protein: 9, carbs: 20, fat: 0.4, sugar: 1.8, fiber: 7.9 },
  { id: 'seed-cicer-vareny', name: 'Cicer vareny', kcal: 164, protein: 8.9, carbs: 27.4, fat: 2.6, sugar: 4.8, fiber: 7.6 },
  { id: 'seed-hrach-vareny', name: 'Hrach vareny', kcal: 118, protein: 8.3, carbs: 21, fat: 0.4, sugar: 2.9, fiber: 8.3 },
  { id: 'seed-tofu', name: 'Tofu natural', kcal: 120, protein: 13, carbs: 2, fat: 7, sugar: 0.5, fiber: 1 },
  { id: 'seed-cibula', name: 'Cibula', kcal: 40, protein: 1.1, carbs: 9.3, fat: 0.1, sugar: 4.2, fiber: 1.7 },
  { id: 'seed-cesnak', name: 'Cesnak', kcal: 149, protein: 6.4, carbs: 33, fat: 0.5, sugar: 1, fiber: 2.1 },
  { id: 'seed-mrkva', name: 'Mrkva', kcal: 41, protein: 0.9, carbs: 9.6, fat: 0.2, sugar: 4.7, fiber: 2.8 },
  { id: 'seed-petrzlen-koren', name: 'Petrzlen koren', kcal: 55, protein: 1.5, carbs: 12, fat: 0.6, sugar: 2.5, fiber: 4.9 },
  { id: 'seed-zeler', name: 'Zeler', kcal: 42, protein: 1.5, carbs: 9.2, fat: 0.3, sugar: 1.6, fiber: 1.8 },
  { id: 'seed-kalerab', name: 'Kalerab', kcal: 27, protein: 1.7, carbs: 6.2, fat: 0.1, sugar: 2.6, fiber: 3.6 },
  { id: 'seed-kapusta-biela', name: 'Kapusta biela', kcal: 25, protein: 1.3, carbs: 5.8, fat: 0.1, sugar: 3.2, fiber: 2.5 },
  { id: 'seed-kapusta-kysla', name: 'Kapusta kysla', kcal: 19, protein: 0.9, carbs: 4.3, fat: 0.1, sugar: 1.8, fiber: 2.9 },
  { id: 'seed-paradajka', name: 'Paradajka', kcal: 18, protein: 0.9, carbs: 3.9, fat: 0.2, sugar: 2.6, fiber: 1.2 },
  { id: 'seed-paprika', name: 'Paprika', kcal: 31, protein: 1, carbs: 6, fat: 0.3, sugar: 4.2, fiber: 2.1 },
  { id: 'seed-uhorka', name: 'Uhorka', kcal: 15, protein: 0.7, carbs: 3.6, fat: 0.1, sugar: 1.7, fiber: 0.5 },
  { id: 'seed-salat-ladovy', name: 'Salat ladovy', kcal: 14, protein: 0.9, carbs: 3, fat: 0.1, sugar: 2, fiber: 1.2 },
  { id: 'seed-brokolica', name: 'Brokolica', kcal: 34, protein: 2.8, carbs: 6.6, fat: 0.4, sugar: 1.7, fiber: 2.6 },
  { id: 'seed-karfiol', name: 'Karfiol', kcal: 25, protein: 1.9, carbs: 5, fat: 0.3, sugar: 1.9, fiber: 2 },
  { id: 'seed-spenat', name: 'Spenat', kcal: 23, protein: 2.9, carbs: 3.6, fat: 0.4, sugar: 0.4, fiber: 2.2 },
  { id: 'seed-hrasok-mrazeny', name: 'Hrasok mrazeny', kcal: 81, protein: 5.4, carbs: 14.5, fat: 0.4, sugar: 5.7, fiber: 5.1 },
  { id: 'seed-kukurica-sterilizovana', name: 'Kukurica sterilizovana', kcal: 96, protein: 3.4, carbs: 21, fat: 1.5, sugar: 4.5, fiber: 2.4 },
  { id: 'seed-sampinony', name: 'Sampinony', kcal: 22, protein: 3.1, carbs: 3.3, fat: 0.3, sugar: 2, fiber: 1 },
  { id: 'seed-cvikla', name: 'Cvikla', kcal: 43, protein: 1.6, carbs: 9.6, fat: 0.2, sugar: 6.8, fiber: 2.8 },
  { id: 'seed-tekvica', name: 'Tekvica', kcal: 26, protein: 1, carbs: 6.5, fat: 0.1, sugar: 2.8, fiber: 0.5 },
  { id: 'seed-avokado', name: 'Avokado', kcal: 160, protein: 2, carbs: 8.5, fat: 14.7, sugar: 0.7, fiber: 6.7 },
  { id: 'seed-hruska', name: 'Hruska', kcal: 57, protein: 0.4, carbs: 15.2, fat: 0.1, sugar: 9.8, fiber: 3.1 },
  { id: 'seed-pomaranc', name: 'Pomaranc', kcal: 47, protein: 0.9, carbs: 11.8, fat: 0.1, sugar: 9.4, fiber: 2.4 },
  { id: 'seed-mandarinka', name: 'Mandarinka', kcal: 53, protein: 0.8, carbs: 13.3, fat: 0.3, sugar: 10.6, fiber: 1.8 },
  { id: 'seed-citron', name: 'Citron', kcal: 29, protein: 1.1, carbs: 9.3, fat: 0.3, sugar: 2.5, fiber: 2.8 },
  { id: 'seed-hrozno', name: 'Hrozno', kcal: 69, protein: 0.7, carbs: 18.1, fat: 0.2, sugar: 15.5, fiber: 0.9 },
  { id: 'seed-jahody', name: 'Jahody', kcal: 32, protein: 0.7, carbs: 7.7, fat: 0.3, sugar: 4.9, fiber: 2 },
  { id: 'seed-cucoriedky', name: 'Cucoriedky', kcal: 57, protein: 0.7, carbs: 14.5, fat: 0.3, sugar: 10, fiber: 2.4 },
  { id: 'seed-maliny', name: 'Maliny', kcal: 52, protein: 1.2, carbs: 12, fat: 0.7, sugar: 4.4, fiber: 6.5 },
  { id: 'seed-slivky', name: 'Slivky', kcal: 46, protein: 0.7, carbs: 11.4, fat: 0.3, sugar: 9.9, fiber: 1.4 },
  { id: 'seed-broskyna', name: 'Broskyna', kcal: 39, protein: 0.9, carbs: 9.5, fat: 0.3, sugar: 8.4, fiber: 1.5 },
  { id: 'seed-marhula', name: 'Marhula', kcal: 48, protein: 1.4, carbs: 11.1, fat: 0.4, sugar: 9.2, fiber: 2 },
  { id: 'seed-hrozienka', name: 'Hrozienka', kcal: 299, protein: 3.1, carbs: 79, fat: 0.5, sugar: 59, fiber: 3.7 },
  { id: 'seed-vlasske-orechy', name: 'Vlasske orechy', kcal: 654, protein: 15, carbs: 14, fat: 65, sugar: 2.6, fiber: 6.7 },
  { id: 'seed-mandle', name: 'Mandle', kcal: 579, protein: 21, carbs: 22, fat: 50, sugar: 4.4, fiber: 12.5 },
  { id: 'seed-lieskovce', name: 'Lieskovce', kcal: 628, protein: 15, carbs: 17, fat: 61, sugar: 4.3, fiber: 9.7 },
  { id: 'seed-arasidy', name: 'Arasidy', kcal: 567, protein: 26, carbs: 16, fat: 49, sugar: 4, fiber: 8.5 },
  { id: 'seed-slnecnicove-semienka', name: 'Slnecnicove semienka', kcal: 584, protein: 21, carbs: 20, fat: 51, sugar: 2.6, fiber: 8.6 },
  { id: 'seed-tekvicove-semienka', name: 'Tekvicove semienka', kcal: 559, protein: 30, carbs: 11, fat: 49, sugar: 1.4, fiber: 6 },
  { id: 'seed-cukor-krystal', name: 'Cukor krystal', kcal: 400, protein: 0, carbs: 100, fat: 0, sugar: 100, fiber: 0 },
  { id: 'seed-med', name: 'Med', kcal: 304, protein: 0.3, carbs: 82, fat: 0, sugar: 82, fiber: 0.2 },
  { id: 'seed-dzem', name: 'Dzem', kcal: 250, protein: 0.4, carbs: 62, fat: 0.1, sugar: 55, fiber: 1 },
  { id: 'seed-kakao', name: 'Kakao', kcal: 228, protein: 20, carbs: 58, fat: 14, sugar: 1.8, fiber: 33 },
  { id: 'seed-horka-cokolada', name: 'Horka cokolada', kcal: 546, protein: 7.8, carbs: 46, fat: 36, sugar: 24, fiber: 11 },
  { id: 'seed-detske-piskoty', name: 'Detske piskoty', kcal: 390, protein: 8, carbs: 78, fat: 5, sugar: 30, fiber: 2 },
  { id: 'seed-puding-prasok', name: 'Puding prasok', kcal: 350, protein: 0.5, carbs: 86, fat: 0.1, sugar: 0.5, fiber: 0.5 },
  { id: 'seed-olej-repkovy', name: 'Repkovy olej', kcal: 884, protein: 0, carbs: 0, fat: 100, sugar: 0, fiber: 0 },
  { id: 'seed-mast', name: 'Bravcova mast', kcal: 900, protein: 0, carbs: 0, fat: 100, sugar: 0, fiber: 0 },
  { id: 'seed-ocot', name: 'Ocot', kcal: 18, protein: 0, carbs: 0.9, fat: 0, sugar: 0.4, fiber: 0 },
  { id: 'seed-kecup', name: 'Kecup', kcal: 112, protein: 1.3, carbs: 26, fat: 0.2, sugar: 22, fiber: 0.3 },
  { id: 'seed-horcica', name: 'Horcica', kcal: 66, protein: 4.4, carbs: 5.8, fat: 3.3, sugar: 2.5, fiber: 3.3 },
  { id: 'seed-majoneza', name: 'Majoneza', kcal: 680, protein: 1, carbs: 1, fat: 75, sugar: 1, fiber: 0 },
  { id: 'seed-tatarska-omacka', name: 'Tatarska omacka', kcal: 520, protein: 1, carbs: 6, fat: 55, sugar: 4, fiber: 0.5 },
  { id: 'seed-pretlak', name: 'Paradajkovy pretlak', kcal: 82, protein: 4.3, carbs: 19, fat: 0.5, sugar: 12, fiber: 4 },
  { id: 'seed-passata', name: 'Paradajkova passata', kcal: 33, protein: 1.6, carbs: 5.8, fat: 0.2, sugar: 4.2, fiber: 1.5 },
  { id: 'seed-leco', name: 'Leco sterilizovane', kcal: 55, protein: 1.5, carbs: 8, fat: 2, sugar: 5, fiber: 2 },
  { id: 'seed-vajecne-rezance-varene', name: 'Vajecne rezance varene', kcal: 138, protein: 4.5, carbs: 25, fat: 2.1, sugar: 0.8, fiber: 1.5 },
  { id: 'seed-halusky-varene', name: 'Halusky varene', kcal: 160, protein: 4.5, carbs: 32, fat: 1.5, sugar: 1, fiber: 2 },
  { id: 'seed-tvarohove-gulky', name: 'Tvarohove gulky', kcal: 190, protein: 9, carbs: 28, fat: 5, sugar: 6, fiber: 1.5 }
];
